<!DOCTYPE html>
<html>

<head>
    <style>
        /* Add your styles here */
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #ddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .metric-container {
            margin-top: 30px;
        }
    </style>
</head>

<body>

    <h1>Adoption Requests Reports</h1>
    <p>Generated at: {{ now()->format('l, F j, Y H:i:s') }}</p>
    <p>Generated by: {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</p>

    <div class="metric-container">
        <h2>Total Adoption Requests: {{ $totalAdoptionRequests }}</h2>
    </div>

    <div class="metric-container">
        <h2>Status Distribution</h2>
        <table>
            <tr>
                <th>Status</th>
                <th>Dog Count</th>
                <th>Cat Count</th>
            </tr>
            @foreach($statusCounts as $status => $counts)
                <tr>
                    <td>{{ ucfirst($status) }}</td>
                    <td>{{ $counts['Dog'] ?? 0 }}</td>
                    <td>{{ $counts['Cat'] ?? 0 }}</td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="metric-container">
        <h2>Adoption Requests</h2>
        <table>
            <tr>
                <th>ID</th>
                <th>Applicant</th>
                <th>Pet</th>
                <th>Type</th>
                <th>Status</th>
                <th>Requested At</th>
            </tr>
            @foreach($adoptionRequests as $adoptionRequest)
                <tr>
                    <td>{{ $adoptionRequest->id }}</td>
                    <td>{{ $adoptionRequest->user->first_name ?? '' }} {{ $adoptionRequest->user->last_name ?? '' }}</td>
                    <td>{{ $adoptionRequest->pet->pet_name ?? 'N/A' }}</td>
                    <td>{{ $adoptionRequest->pet->type ?? 'N/A' }}</td>
                    <td>{{ ucfirst($adoptionRequest->adoptionStatus->status ?? 'N/A') }}</td>
                    <td>{{ $adoptionRequest->created_at }}</td>
                </tr>
            @endforeach
        </table>
    </div>
</body>

</html>
