<!DOCTYPE html>
<html>

<head>
    <style>
        /* Add your styles here */
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #ddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .metric-container {
            margin-top: 30px;
        }
    </style>
</head>

<body>

    <h1>Missing Pets Reports</h1>

    <!-- Generated at and by information -->
    <p>Generated at: {{ now()->format('l, F j, Y H:i:s') }}</p>
    <p>Generated by: {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</p>

    <!-- Total Missing Pets Section -->
    <div class="metric-container">
        <h2>Total Missing Pets: {{ $totalMissingPets }}</h2>
        <p>Overview of all missing pets.</p>
    </div>

    <!-- Missing Dogs Section -->
    <div class="metric-container">
        <h2>Missing Dogs</h2>
        <table>
            <tr>
                <th>Status</th>
                <th>Count</th>
            </tr>
            @foreach($statusCountsDogs as $status => $count)
            <tr>
                <td>{{ $status }}</td>
                <td>{{ $count }}</td>
            </tr>
            @endforeach
        </table>
        <p>Status distribution of missing dogs.</p>
    </div>

    <!-- Missing Cats Section -->
    <div class="metric-container">
        <h2>Missing Cats</h2>
        <table>
            <tr>
                <th>Status</th>
                <th>Count</th>
            </tr>
            @foreach($statusCountsCats as $status => $count)
            <tr>
                <td>{{ $status }}</td>
                <td>{{ $count }}</td>
            </tr>
            @endforeach
        </table>
        <p>Description: Status distribution of missing cats.</p>
    </div>

    <!-- Add other sections as needed -->
    

</body>

</html>
