<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Reports</title>
    <style>
        /* Add any custom styles for your PDF here */
        body {
            font-family: Arial, sans-serif;
        }
        h1, h2 {
            text-align: left; /* Align headers to the left */
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        .footer {
            text-align: left; /* Align footer to the left */
        }
    </style>
</head>
<body>
    <h1>Pet Reports</h1>

    {{-- Generated Info --}}
    <div class="footer">
    <p>Generated at: {{ now()->format('F j, Y \a\t g:i A') }}</p>

        @auth
            <p>Generated by: {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</p>
        @endauth
    </div>

    {{-- Table 1: Summary of Adopted Pets --}}
    <h2>Summary of Adopted Pets (Last 12 Months)</h2>
    <p>This table provides a summary of adopted pets over the last 12 months.</p>
    <table>
        <!-- Metric Table 1 -->
        <thead>
            <tr>
                <th>Metric</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total Adopted Pets (Last 12 Months)</td>
                <td>{{ $adoptedPets->count() }}</td>
            </tr>
            <tr>
                <td>Male (Last 12 Months)</td>
                <td>{{ $adoptedPets->where('gender', 'Male')->count() }}</td>
            </tr>
            <tr>
                <td>Female (Last 12 Months)</td>
                <td>{{ $adoptedPets->where('gender', 'Female')->count() }}</td>
            </tr>
            <!-- Add more metrics as needed -->
        </tbody>
    </table>

    {{-- Table 2: Summary of Pets Available for Adoption --}}
    <h2>Summary of Pets Available for Adoption</h2>
    <p>This table provides a summary of pets currently available for adoption.</p>
    <table>
        <!-- Metric Table 2 -->
        <thead>
            <tr>
                <th>Metric</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total Pets Available for Adoption</td>
                <td>{{ $petsForAdoption->count() }}</td>
            </tr>
            <tr>
                <td>Dogs Available for Adoption</td>
                <td>{{ $petsForAdoption->where('type', 'Dog')->count() }}</td>
            </tr>
            <tr>
                <td>Cats Available for Adoption</td>
                <td>{{ $petsForAdoption->where('type', 'Cat')->count() }}</td>
            </tr>
            <!-- Add more metrics as needed -->
        </tbody>
    </table>

    {{-- Table 3: Total Dogs and Cats --}}
    <h2>Total Dogs and Cats</h2>
    <p>This table provides a total count of dogs and cats.</p>
    <table>
        <!-- Metric Table 3 -->
        <thead>
            <tr>
                <th>Type</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total Dogs</td>
                <td>{{ $totalDogs }}</td>
            </tr>
            <tr>
                <td>Total Cats</td>
                <td>{{ $totalCats }}</td>
            </tr>
        </tbody>
    </table>
</body>
</html>
