<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1, h2, h3 {
            color: #333;
        }

        h1 {
            font-size: 28px;
            margin-bottom: 10px;
        }

        h2 {
            padding-bottom: 5px;
            margin-bottom: 20px;
            font-size: 24px;
        }

        h3 {
            margin-bottom: 10px;
            font-size: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table, th, td {
            border: 1px solid #333;
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        section {
            margin-bottom: 30px;
        }

        p {
            color: #555;
            font-size: 16px;
            margin-bottom: 15px;
        }

        .footer {
            margin-top: 30px;
            font-size: 14px;
            color: #777;
        }

        /* Landscape (folio) format */
        @page {
            size: folio portrait;
        }
    </style>
</head>


<body>

    <h1>Animal Welfare Reports</h1>
    <p>Generated on: {{ now()->format('F j, Y \a\t g:i A') }}</p>
    <p>Generated by: {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</p>

    <!-- Total Reports -->
    <section>
        <h2>Total Reports</h2>
        <p>This section provides an overview of the total number of animal welfare reports.</p>
        <table>
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Total Reports</td>
                    <td>{{ $totalReports }}</td>
                </tr>
            </tbody>
        </table>
    </section>

    <!-- Status Distribution -->
    <section>
        <h2>Status Distribution</h2>
        <p>Explore the distribution of reports based on their status.</p>
        <table>
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($statusCounts as $status => $count)
                    <tr>
                        <td>{{ $status }}</td>
                        <td>{{ $count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </section>

    <!-- Case Type Distribution -->
    <section>
        <h2>Distribution by Case Type</h2>
        <p>Explore the distribution of reports based on different case types.</p>

        <!-- Dog Table -->
        <h3>Dog Cases</h3>
        <p>Details of reports related to dogs.</p>
        <table>
            <thead>
                <tr>
                    <th>Case Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($caseTypeCounts as $caseType => $count)
                    @if (stripos($caseType, 'dog') !== false)
                        <tr>
                            <td>{{ $caseType }}</td>
                            <td>{{ $count }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>

        <!-- Cat Table -->
        <h3>Cat Cases</h3>
        <p>Details of reports related to cats.</p>
        <table>
            <thead>
                <tr>
                    <th>Case Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($caseTypeCounts as $caseType => $count)
                    @if (stripos($caseType, 'cat') !== false)
                        <tr>
                            <td>{{ $caseType }}</td>
                            <td>{{ $count }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>

        <!-- Others Table -->
        <h3>Other Cases</h3>
        <p>Details of reports related to other case types.</p>
        <table>
            <thead>
                <tr>
                    <th>Case Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($caseTypeCounts as $caseType => $count)
                    @if (stripos($caseType, 'dog') === false && stripos($caseType, 'cat') === false)
                        <tr>
                            <td>{{ $caseType }}</td>
                            <td>{{ $count }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    </section>

    <div class="footer">
        <p>Animal Welfare Reports - Powered by CritterCare</p>
    </div>

</body>

</html>
